version: '3'
services:
  nodejs:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db_test
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"

